"""claim_map.yaml must cover every results file report.py regenerates.

The manuscript used to carry ~20 inline "(Source: results/x.json)" markers in running
prose. G5a removed them and replaced them with one Appendix C table generated from
claim_map.yaml. That trade is only safe if the mapping cannot fall behind: adding a
generator to report.py without adding a claim-map row would silently leave a reported
number with no stated provenance, which is exactly what the inline markers were there to
prevent.
"""
import pytest
import yaml

from constants import ONCHAIN_PRESENT, ONCHAIN_RESULTS, PKG_DIR
from test_report_regeneration import REGENERATED

CLAIM_MAP = PKG_DIR / "claim_map.yaml"


def _claims():
    with open(CLAIM_MAP, encoding="utf-8") as f:
        return yaml.safe_load(f)["claims"]


def test_claim_map_parses_and_has_required_fields():
    claims = _claims()
    assert claims, "claim_map.yaml carries no claims"
    for c in claims:
        for field in ("claim", "label", "file", "key"):
            assert field in c and str(c[field]).strip(), f"claim missing {field}: {c}"


def test_no_row_carries_a_hand_typed_section_number():
    """`section: "6"` is what this table used to carry, and twelve of twenty-two rows
    had drifted from the section they named before G5b replaced them with labels. A
    literal number has no referent, so nothing can check it. Fail if one comes back."""
    stale = [c["claim"] for c in _claims() if "section" in c]
    assert not stale, (
        f"{len(stale)} row(s) carry a hand-typed `section:` again instead of `label:`, "
        f"which is the field that drifted: {stale}"
    )


def test_every_label_resolves_in_the_aux():
    """Every label in the claim map must exist in fc27.aux.

    tab_claimmap.tex emits \\ref{label} for the Sec. column, so a label that is missing
    or misspelled prints "??" in the submitted PDF. pdflatex reports that as an
    undefined reference and build_fc27.py counts those, but this test names the offending
    claim-map row, which the build log does not. Skips when the paper has not been built
    in this tree, because the .aux is a build product and not every checkout has one."""
    import re

    aux = PKG_DIR.parent / "paper" / "fc27" / "fc27.aux"
    if not aux.exists():
        pytest.skip("fc27.aux absent; build the paper first (python tools/build_fc27.py)")

    defined = set(re.findall(r"\\newlabel\{([^}]+)\}", aux.read_text(encoding="utf-8")))
    missing = sorted({c["label"] for c in _claims()} - defined)
    assert not missing, (
        f"claim_map.yaml names {len(missing)} label(s) that fc27.aux does not define, so "
        f"Appendix C's Sec. column would print ?? for them: {missing}"
    )


def test_every_regenerated_results_file_is_mapped():
    """Every file report.py regenerates must appear in the claim map."""
    mapped = {c["file"] for c in _claims()}
    missing = sorted(REGENERATED - mapped)
    assert not missing, (
        f"{len(missing)} results file(s) regenerated by report.py have no claim_map.yaml "
        f"row, so a reported number would have no stated provenance: {missing}"
    )


def test_claim_map_names_no_unknown_file():
    """The reverse direction: a claim-map row naming a file nothing produces is a stale
    row, and would print a dead provenance pointer into Appendix C."""
    mapped = {c["file"] for c in _claims()}
    unknown = sorted(mapped - REGENERATED)
    assert not unknown, (
        f"claim_map.yaml names {len(unknown)} file(s) report.py does not regenerate: "
        f"{unknown}"
    )


def _resolve(doc, key: str):
    """Literal key first, then dotted path.

    Literal-first is load-bearing: several real keys contain a dot of their own
    (feed_trough_only_at_phi_0.08, cross_feed_range_at_phi_0.08). Splitting those on
    "." reports a key that exists as missing, which is how the first pass of this
    check over-counted the drift it was written to find."""
    if isinstance(doc, dict) and key in doc:
        return True
    cur = doc
    for part in key.split("."):
        if isinstance(cur, dict) and part in cur:
            cur = cur[part]
        else:
            return False
    return True


def test_every_key_resolves_in_the_results_file_it_names():
    """The `key` column must name something the file actually contains.

    This is the same disease the `section:` field had, in the column nobody looked at.
    A key is a literal string with no referent, so it drifts silently as a generator's
    schema changes -- and unlike `section:`, it is printed straight into Appendix C's
    claim map, which is the paper's own reproducibility contract. When this check was
    first written (G7.3, 2026-09-12) 18 of the 22 rows named a key absent from the file
    they point at, and the full suite passed anyway, because every other test here reads
    the yaml and the aux file but never opens a results JSON. Two independent audit lanes
    found it before any reader did."""
    import json

    bad = []
    for c in _claims():
        name = str(c["file"]).strip()
        path = PKG_DIR / "results" / name
        if not path.exists():
            # Absent BY DESIGN in the short paper's artifact: the on-chain analyses
            # belong to the long paper and are not shipped. Not a broken row.
            if not ONCHAIN_PRESENT and name in ONCHAIN_RESULTS:
                continue
            bad.append(f"{c['claim']}: no such results file {c['file']}")
            continue
        doc = json.loads(path.read_text(encoding="utf-8"))
        for key in (k.strip() for k in str(c["key"]).split(",")):
            if not _resolve(doc, key):
                bad.append(f"{c['claim']}: {c['file']} has no key {key!r}")
    assert not bad, (
        f"{len(bad)} claim-map key(s) do not resolve in the file they name:\n  "
        + "\n  ".join(bad)
    )


def test_any_source_capture_exists_and_is_hashed():
    """A row may name the frozen primary source its number was read off.

    The field is optional, but where it is present it has to be real and hashed,
    otherwise it is decoration: the whole point is that a reader can open the capture
    and check the transcription against it. Requiring a manifest entry is what stops a
    path being named that nothing verifies, which is how phi = 0.08 came to have a
    bibliography citation and no capture for the life of the project."""
    import json

    manifest_path = PKG_DIR / "data" / "MANIFEST.json"
    if not manifest_path.exists():
        pytest.skip("MANIFEST.json absent")
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    # A capture may be pinned in EITHER section. files{} carries a hash for a derived or
    # bundled artifact; sources[] carries one for a fetched artifact, alongside its URL
    # and retrieval time. Checking only files{} reported an untracked capture for a file
    # that is in fact tracked, with strictly more provenance than files{} would give.
    pinned = set(manifest.get("files", {}))
    pinned |= {s["file"] for s in manifest.get("sources", [])
               if s.get("file") and s.get("sha256")}

    bad = []
    for c in _claims():
        rel = str(c.get("source_capture") or "").strip()
        if not rel:
            continue
        if not (PKG_DIR / "data" / rel).exists():
            bad.append(f"{c['claim']}: source_capture {rel} does not exist")
        elif rel not in pinned:
            bad.append(f"{c['claim']}: source_capture {rel} is hashed in neither "
                        f"MANIFEST files{{}} nor sources[]")
    assert not bad, "\n  ".join(["source_capture problems:"] + bad)


def test_generated_fragment_is_current():
    """tables.py must have been re-run after the last claim_map.yaml edit.

    Filenames are set with \\path, which takes _ literally, so the fragment carries the
    name exactly as claim_map.yaml spells it and no escaping is applied here. The map is
    emitted as two fragments (the single 22-row float printed its last row off the bottom
    of the page), so a claim may land in either and this checks their concatenation."""
    tables = PKG_DIR.parent / "paper" / "fc27" / "tables"
    if not tables.parent.exists():
        pytest.skip("full paper absent; the printed claim map lives only in it")
    frags = [tables / "tab_claimmap.tex", tables / "tab_claimmap_b.tex"]
    for frag in frags:
        assert frag.exists(), f"{frag.name} has not been generated; run python tables.py"
    text = "\n".join(f.read_text(encoding="utf-8") for f in frags)
    for c in _claims():
        assert str(c["file"]) in text, (
            f"{c['file']} is in claim_map.yaml but not in the generated fragment; "
            f"re-run python tables.py"
        )
        assert rf"\ref{{{c['label']}}}" in text, (
            f"{c['claim']} is mapped to {c['label']} but the fragment carries no "
            f"\\ref for it; re-run python tables.py"
        )
