"""Guards report.py's regeneration coverage: it must regenerate EVERY results/*.json.

Before this fix, ten of twenty-two results files were each produced by a standalone
script's own __main__ block and never wired into report.py, so the documented five-step
reproduction sequence (data_fetch.py verify -> data_fetch_n1.py verify -> redemptions.py
--from-frozen -> pytest -> report.py) could not regenerate them. That let one of them,
results/trough_corroboration.json, go stale against its own generator with nothing
catching it, every in-tree check, including a fresh clean-clone comparison, scored it
as "agreeing" because neither side ever regenerated it.

REGENERATED is the explicit, hand-maintained list this test enforces both directions: a
file on disk NOT in this list means a producer was added without being wired into
report.py (the exact defect that caused the staleness), and a name in this list with NO
file on disk means report.py's write set and the actual results/ directory have diverged
the other way. Either direction fails loudly here rather than staying invisible until a
clean clone.
"""
from pathlib import Path

from constants import RESULTS_DIR, ONCHAIN_PRESENT, ONCHAIN_RESULTS

REGENERATED = {
    "fifo_rule.json",
    "hourly_counts.json",
    "impossibility_window.json",
    "makewhole_timing.json",
    "number1_nonfundamental_share.json",
    "number1b_rational_bound.json",
    "number2_redemption_hhi.json",
    "number3_placebo.json",
    "number4_dai_contagion.json",
    "ordering_null.json",
    "panel_11mar.json",
    "phi_cash_leg_scenarios.json",
    "phi_denominator_sensitivity.json",
    "phi_dynamic.json",
    "placebo_excluded_coins.json",
    "second_event_terra.json",
    "specificity_panel.json",
    "subfloor_depth_live.json",
    "time_value.json",
    "trough_corroboration.json",
    "trough_volume.json",
    "tusd_2023.json",
    "usdt_premium.json",
    "usdt_premium_timing.json",
}


def test_every_results_json_on_disk_is_in_the_regenerated_set():
    on_disk = {p.name for p in RESULTS_DIR.glob("*.json")}
    extra = on_disk - REGENERATED
    assert not extra, (
        f"results/*.json contains file(s) not regenerated by report.py: {sorted(extra)} "
        f"-- either wire their producer into report.py's main(), or if a file is "
        f"genuinely not reproducible offline (like redemptions_by_wallet.csv's FIFO "
        f"input), document the exception explicitly here rather than leaving it silent."
    )


def test_every_regenerated_name_actually_exists_on_disk():
    on_disk = {p.name for p in RESULTS_DIR.glob("*.json")}
    # The on-chain results are not shipped in the short paper's artifact, so in that
    # tree they are legitimately absent rather than missing.
    expected = REGENERATED if ONCHAIN_PRESENT else REGENERATED - ONCHAIN_RESULTS
    missing = expected - on_disk
    assert not missing, (
        f"REGENERATED lists file(s) not present in results/: {sorted(missing)} -- this "
        f"list has drifted from what report.py actually writes; update it to match."
    )


def test_report_source_references_every_regenerated_filename():
    """Cheaper than actually running report.py (which takes several minutes): assert
    report.py's own source text mentions every filename in REGENERATED, so a name
    quietly dropped from main() without updating this list still gets caught. This is a
    static check, not a substitute for actually running report.py and diffing the
    output, that happens in the reproduction gate, not here."""
    src = (Path(__file__).resolve().parent.parent / "report.py").read_text(encoding="utf-8")
    missing = sorted(name for name in REGENERATED if name not in src)
    assert not missing, (
        f"report.py's source does not mention: {missing} -- if these are genuinely "
        f"regenerated by a different path (e.g. inside figures.py/tables.py rather than "
        f"a direct json.dump in report.py itself), adjust this check; otherwise wire "
        f"them in."
    )
